import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";
import Cart from "@/components/cart";
import { Banner } from "@/components/banner";
import AutoPlayVideoSlider from "@/components/videobanner";
import HeaderAndVideo from "@/components/headerandvido";
import { InViewContextProvider } from "@/components/inviewcontext";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-lightAlmond`}>
        <Banner />
        <InViewContextProvider>
          <HeaderAndVideo />

          {children}
          <Footer />
        </InViewContextProvider>
      </body>
    </html>
  );
}
